name: syncfusion_flutter_pdf
description: Syncfusion Flutter PDF is a library written natively in Dart for creating PDF documents from scratch.
version: 18.1.36-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdf

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  xml:
  syncfusion_flutter_core:
